### ISSUE TITLE
Monitor methods don't always execute in presence of Failures?

### ISSUE THREAD

**Issue by japhb** [jnthn/oo-monitors#9] opened 2016-12-30 23:47 UTC
I've golfed this down from a much larger example in the Terminal::Print module, but this version is completely independent and self contained, and tested against both OO::Monitors 1.0 and 1.1 (both with 'no precompilation' at the top to take that out of the equation).

Comments are inline, but run this in a large terminal window and the glitches (which show up as 'BUG') should be obvious within a few frames.  These glitches seem to depend both on Grid being a monitor instead of a normal class, and the Failure creation (and defanging) in the inner loop.

There are also a couple occasional bugs that produce mysterious errors or outright crashes, also mentioned in the comments below.

```
use OO::Monitors;

# Only shows glitches when a monitor instead of a class
# class Grid {
monitor Grid {
    has $.w;
    has $.h;
    has @.grid;

    method change-cell($x, $y, $s) {
        @!grid[$y][$x] = $s;
    }

    # Very weird occasional crash bug if this is commented out:
    #    Cannot resolve caller infix:<div>(Nil, Int)
    # method Str() { '' }
}


my $w    = +q:x{ tput cols  };
my $h    = +q:x{ tput lines };
my $grid = Grid.new(:$w, :$h);

for ^10 {
    # Occasionally produces "Use of Nil in numeric context"
    $grid.grid = [ [ 'BUG' xx $grid.w ] xx $grid.h ];

    for ^$grid.h -> $y {
        for ^($grid.w div 2) -> $x {
            Failure.new() // '';  # Triggers glitches
            # Exception.new() // '';  # Doesn't glitch

            $grid.change-cell($x * 2,     $y, ' |');
            $grid.change-cell($x * 2 + 1, $y, ''  );
        }
    }

    # ANSI command here just makes image easier to watch, but can be removed
    print ^$h .map({ "\e[{ $_ + 1 };1H" ~ $grid.grid[$_].join });
    sleep 1;
}
```

**Comment by jnthn** [comment] 2017-01-02 19:24
So, the good news is that I can reproduce it. I've golfed it further to still get the errors, but eliminate most I/O and the sleep, to make it quicker/easier to examine, and a smaller test case.

```
use OO::Monitors;

# Only shows glitches when a monitor instead of a class
# class Grid {
monitor Grid {
    has $.w;
    has $.h;
    has @.grid;

    method change-cell($x, $y, $s) {
        @!grid[$y][$x] = $s;
    }

    # Very weird occasional crash bug if this is commented out:
    #    Cannot resolve caller infix:<div>(Nil, Int)
    # method Str() { '' }
}

my $w    = 90;
my $h    = 25;
my $grid = Grid.new(:$w, :$h);

for ^10 {
    $grid.grid = [ [ 'BUG' xx $grid.w ] xx $grid.h ];

    for ^$grid.h -> $y {
        for ^($grid.w div 2) -> $x {
            Failure.new() // '';  # Triggers glitches

            $grid.change-cell($x * 2,     $y, ' |');
            $grid.change-cell($x * 2 + 1, $y, ''  );
        }
    }

    die "BUG" if (^$h .map({ "\e[{ $_ + 1 };1H" ~ $grid.grid[$_].join })) ~~ /BUG/;
    say "OK";
}
```

So far, I've found:

* It's not sensitive to any of the MoarVM dynamic optimization features (so, that excludes a whole class of issues)
* It's not a data race because there's only a single thread running
* It shows up both with and without precompilation
* The number of iterations before the issue appears changes with small changes to the program
* It's sensitive to how often we GC (tweaking GC nursery size moves iteration count; for example 15711 bytes reliably makes it produce BUG the first iteration)
* However, none of our GC debugging mode, our fixed size allocator debug mode, or valgrind have anything to say about it

I've then started to gut OO::Monitors to see what elements produce the issue. I got it down to:

```
class MetamodelX::MonitorHOW is Metamodel::ClassHOW {
    method add_method(Mu \type, $name, $meth) {
        my &callsame := CORE::<&callsame>; # Workaround for RT #127858
        my $leaving = 0;
        $name ne 'BUILDALL' && $meth.wrap(-> \SELF, | {
            LEAVE $leaving++;
            callsame
        });
        self.Metamodel::ClassHOW::add_method(type, $name, $meth);
    }
    
    method compose(Mu \type) {
        self.Metamodel::ClassHOW::compose(type);
    }   
}   

my package EXPORTHOW {
    package DECLARE {
        constant monitor = MetamodelX::MonitorHOW;
    }   
}   
```

With a small GC nursery, commenting out the `LEAVE` line hides the BUG, though leaves the "Use of Nil in string context" reliably happening. Without the `Failure` being created, both are gone even with the `Failure` being produced.

Weird? Oh yes. Enough hunting for today, will continue tomorrow or Wednesday.

**Comment by jnthn** [comment] 2017-01-03 15:12
Tracked down to an issue involving callsame and finalizers, which is why `Failure` triggers it (it has a `DESTROY` method). Seems the `LEAVE` just made it a bit more likely to happen, but wasn't particularly involved. Fix ongoing in all of MoarVM/NQP/Rakudo.

**Comment by jnthn** [comment] 2017-01-03 18:08
Fixed in MoarVM/NQP/Rakudo HEAD. I managed to golf a reproduction all the way down to something that could be added as an [integration test](https://github.com/perl6/roast/blob/master/integration/failure-and-callsame.t).

**Closed by jnthn** 2017-01-03 18:08 UTC
